plugins {
    id "com.android.application"
}

android {
    namespace "online.mask0fdark.m0d"
    compileSdk 34

    defaultConfig {
        applicationId "online.mask0fdark.m0d"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
}
